USE bd_moocycle;

INSERT INTO tbl_races (nom)
VALUES ("Holstein"),
    ("Charolaise"),
    ("Limousine"),
    ("Normande"),
    ("Montbéliarde"),
    ("Salers"),
    ("Tarentaise"),
    ("Aubrac"),
    ("Brune des Alpes"),
    ("Vosgienne"),
    ("Gasconne"),
    ("Parthenaise"),
    ("Rouge Flamande"),
    ("Pie Rouge"),
    ("Abondance"),
    ("Simmental"),
    ("Hereford"),
    ("Angus"),
    ("Jersey"),
    ("Guernesey"),
    ("Blonde d'Aquitaine"),
    ("Bleue du Nord"),
    ("Pie Noire Bretonne"),
    ("Maine-Anjou"),
    ("Galloway"),
    ("Dexter"),
    ("Highland"),
    ("Bazadaise"),
    ("Shorthorn"),
    ("Devon"),
    ("Longhorn"),
    ("Red Poll"),
    ("Beefmaster"),
    ("Brahman"),
    ("Santa Gertrudis"),
    ("Nelore"),
    ("Gir"),
    ("Sahiwal"),
    ("Tharparkar");